---
services:
  mongo:
    image: mongo
    env_file:
      - .env.dev
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    env_file:
      - .env.dev
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  mongo: