---
services:
  mongo:
    image: mongo:8.0.6-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo:/data/db
    networks:
      mongo:
    ports:
      - ${MONGO_PORT}:27017

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    networks:
      mongo:
    depends_on:
      - mongo

volumes:
  mongo:

networks:
  mongo:
