---
services:
  mongo:
    image: mongo:8.0.5
    hostname: mongodb
    volumes:
      - mongo:/data/db/
    ports:
      - 27017:27017
    networks:
      - mongo

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    networks:
      - mongo
    depends_on:
      - mongo

volumes:
  mongo:

networks:
  mongo:
